import type { GlossaryTerm } from './types'

export const glossaryTerms: GlossaryTerm[] = [
  // BASICS (1-20)
  {
    id: 'atm', term: 'ATM', category: 'basics', emoji: '🏧',
    definition: 'Automated Teller Machine — A machine that lets you withdraw or deposit money 24/7.',
    example: 'Think of it like a vending machine for your own cash.',
    detailedExample: 'ATMs are networked telecommunication devices that enable clients of financial institutions to perform financial transactions, such as cash withdrawals, deposits, transfer of funds, or obtaining account information, at any time and without the need for direct interaction with bank staff.',
  },
  {
    id: 'bank', term: 'Bank', category: 'basics', emoji: '🏛️',
    definition: 'A secure place to store money and access financial services sanctioned by the government.',
    example: 'A digital vault with extra features to help you manage your money.',
  },
  {
    id: 'checking-account', term: 'Checking Account', category: 'basics', emoji: '💳',
    definition: 'A bank account used for daily spending and paying bills with frequent transactions.',
    example: 'Your "active" wallet for money you plan to use this month.',
  },
  {
    id: 'savings-account', term: 'Savings Account', category: 'basics', emoji: '💰',
    definition: 'An account meant for storing money for future goals, usually earning small interest.',
    example: 'A "waiting room" for money you don’t need to spend yet.',
  },
  {
    id: 'debit-card', term: 'Debit Card', category: 'basics', emoji: '🏧',
    definition: 'A card that subtracts money directly from your checking account when you buy something.',
    example: 'An electronic instruction that tells the bank to immediately subtract money.',
  },
  {
    id: 'credit-card', term: 'Credit Card', category: 'basics', emoji: '💳',
    definition: 'A card that lets you borrow money up to a limit for purchases, requiring monthly repayment.',
    example: 'A "loan" in your pocket that resets every time you pay it off.',
  },
  {
    id: 'interest-earned', term: 'Interest (Earned)', category: 'basics', emoji: '📈',
    definition: 'Money a bank pays you for keeping your money in a savings account.',
    example: 'A "thank you" fee the bank pays you for letting them hold your money.',
  },
  {
    id: 'budget', term: 'Budget', category: 'basics', emoji: '📋',
    definition: 'A plan that tracks your income (money in) and expenses (money out).',
    example: 'A roadmap that tells your money where to go instead of wondering where it went.',
  },
  {
    id: 'emergency-fund', term: 'Emergency Fund', category: 'basics', emoji: '🚨',
    definition: 'Cash set aside for unexpected costs like car repairs or medical bills.',
    example: 'A financial "umbrella" for a rainy day.',
  },
  {
    id: 'inflation', term: 'Inflation', category: 'markets', emoji: '🎈',
    definition: 'The steady rise in prices over time, making your dollar buy less than it used to.',
    example: 'A $1 candy bar slowly costing $1.50 a few years later.',
    imageUrl: 'https://images.unsplash.com/photo-1543286386-713bdd548da4?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'compound-interest', term: 'Compound Interest', category: 'basics', emoji: '❄️',
    definition: 'Earning interest on your interest, causing your money to grow exponentially over time.',
    example: 'A snowball rolling down a hill—the bigger it gets, the faster it grows.',
    imageUrl: 'https://images.unsplash.com/photo-1611974714851-48206138d73e?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: 'diversification', term: 'Diversification', category: 'basics', emoji: '🧺',
    definition: 'Spreading your investments across many different assets to reduce overall risk.',
    example: 'Not putting all your eggs in one basket.',
    imageUrl: 'https://www.investopedia.com/thmb/hN0Xy1l2S6fP6T2z-2m7vYwVl-g=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Portfolio-Diversification-700x700-1-5c8e25d481744883907a389d4948a3e0.jpg',
  },
  {
    id: 'asset', term: 'Asset', category: 'basics', emoji: '🏠',
    definition: 'Anything of value that you own, such as cash, stocks, or real estate.',
    example: 'The building blocks of your wealth.',
  },
  {
    id: 'liability', term: 'Liability', category: 'basics', emoji: '📉',
    definition: 'Anything that costs you money or represents a debt you owe to someone else.',
    example: 'A weight in your financial backpack.',
  },
  {
    id: 'net-worth', term: 'Net Worth', category: 'basics', emoji: '💎',
    definition: 'The total value of all your assets minus all your liabilities.',
    example: 'Your financial "scorecard" after you pay all your debts.',
  },

  // STOCKS & OWNERSHIP (21-40)
  {
    id: 'stock', term: 'Stock', category: 'stocks', emoji: '📜',
    definition: 'A certificate of ownership in a company. Buying stock makes you a part-owner.',
    example: 'Buying a slice of a pizza. The whole pizza is the company.',
  },
  {
    id: 'share', term: 'Share', category: 'stocks', emoji: '🍕',
    definition: 'The smallest unit of ownership in a company.',
    example: 'The actual slice of pizza in your hand.',
  },
  {
    id: 'ticker-symbol', term: 'Ticker Symbol', category: 'stocks', emoji: '🔠',
    definition: 'A 1-5 letter abbreviation used to identify a specific stock (e.g., AAPL for Apple).',
    example: 'A nickname for a company on the trading floor.',
  },
  {
    id: 'dividend', term: 'Dividend', category: 'stocks', emoji: '🎁',
    definition: 'A portion of a company\'s profit paid out to shareholders as a reward for owning the stock.',
    example: 'A landlord paying you rent just for owning part of the building.',
  },
  {
    id: 'blue-chip', term: 'Blue Chip', category: 'stocks', emoji: '💎',
    definition: 'Stocks of large, well-established, and financially sound companies with a long history of growth.',
    example: 'In poker, blue chips are worth the most. These are the "heavyweight" stocks.',
  },
  {
    id: 'growth-stock', term: 'Growth Stock', category: 'stocks', emoji: '🚀',
    definition: 'A company expected to grow at a much faster rate than the average for the market.',
    example: 'A rocket ship—exciting and fast, but can be a wild ride.',
  },
  {
    id: 'value-stock', term: 'Value Stock', category: 'stocks', emoji: '🏷️',
    definition: 'A stock that tends to trade at a lower price relative to its fundamentals like dividends or earnings.',
    example: 'Buying a high-quality item on sale at a thrift store.',
  },
  {
    id: 'penny-stock', term: 'Penny Stock', category: 'stocks', emoji: '🪙',
    definition: 'Low-priced stocks of small companies, typically trading for less than $5 per share.',
    example: 'A lottery ticket—cheap to buy, but very unlikely to win big.',
  },
  {
    id: 'ipo', term: 'IPO', category: 'stocks', emoji: '🆕',
    definition: 'Initial Public Offering — The first time a private company sells its shares to the general public.',
    example: 'A "Grand Opening" for a company on the stock market.',
  },
  {
    id: 'preferred-stock', term: 'Preferred Stock', category: 'stocks', emoji: '🌟',
    definition: 'A class of ownership in a corporation that has a higher claim on its assets and earnings than common stock.',
    example: 'A VIP pass that gets you paid before everyone else if things go wrong.',
  },

  // MARKET DYNAMICS (41-60)
  {
    id: 'bull-market', term: 'Bull Market', category: 'markets', emoji: '🐂',
    definition: 'A market condition where prices are rising or expected to rise.',
    example: 'A bull thrusts its horns UP.',
    imageUrl: 'https://www.investopedia.com/thmb/Jz9C_LwJ5D6-b8k2r_oWJ0-E16o=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/BullvsBear_Final-5bfc254dc9e77c00511f5e8f.jpg',
  },
  {
    id: 'bear-market', term: 'Bear Market', category: 'markets', emoji: '🐻',
    definition: 'A market condition where prices are falling or expected to fall.',
    example: 'A bear swipes its claws DOWN.',
    imageUrl: 'https://www.investopedia.com/thmb/Jz9C_LwJ5D6-b8k2r_oWJ0-E16o=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/BullvsBear_Final-5bfc254dc9e77c00511f5e8f.jpg',
  },
  {
    id: 'volatility', term: 'Volatility', category: 'markets', emoji: '🎢',
    definition: 'A measure of how much a stock\'s price swings up and down over a period of time.',
    example: 'A roller coaster (high volatility) vs. a steady escalator (low volatility).',
  },
  {
    id: 'liquidity', term: 'Liquidity', category: 'markets', emoji: '💧',
    definition: 'How easily an asset can be turned into cash without affecting its market price.',
    example: 'Cash is perfectly liquid. A house is "frozen" because it takes months to sell.',
  },
  {
    id: 'exchange', term: 'Stock Exchange', category: 'markets', emoji: '🏛️',
    definition: 'A marketplace where stocks, bonds, and other securities are bought and sold (e.g., NYSE, NASDAQ).',
    example: 'The marketplace for companies, like Amazon is for products.',
  },
  {
    id: 'index', term: 'Index', category: 'markets', emoji: '📊',
    definition: 'A collection of stocks that tracks the performance of a specific market or sector.',
    example: 'A "class average" for a group of stocks.',
  },
  {
    id: 'sp500', term: 'S&P 500', category: 'markets', emoji: '🇺🇸',
    definition: 'An index that tracks the 500 largest public companies in the United States.',
    example: 'The "Top 500" leaderboard for the US economy.',
  },
  {
    id: 'nasdaq-composite', term: 'NASDAQ', category: 'markets', emoji: '💻',
    definition: 'An index heavily weighted toward technology and growth companies.',
    example: 'The "tech league" of the market.',
  },
  {
    id: 'dow-jones', term: 'Dow Jones (DJIA)', category: 'markets', emoji: '🏭',
    definition: 'An index tracking 30 major industrial and blue-chip US companies.',
    example: 'The "Old Guard" — its the blue-chip leaderboard.',
  },
  {
    id: 'etf', term: 'ETF', category: 'markets', emoji: '📦',
    definition: 'Exchange-Traded Fund — A fund that tracks an index but trades on an exchange like a single stock.',
    example: 'A "variety pack" of chips instead of buying one bag at a time.',
  },
  {
    id: 'mutual-fund', term: 'Mutual Fund', category: 'markets', emoji: '🤝',
    definition: 'An investment program funded by shareholders that trades in diversified holdings professionally managed.',
    example: 'A "potluck dinner" where everyone brings a dish (money) and shares the feast.',
  },
  {
    id: 'recession', term: 'Recession', category: 'markets', emoji: '🌧️',
    definition: 'A significant decline in economic activity lasting more than a few months.',
    example: 'The whole economy catching a cold.',
  },
  {
    id: 'correction', term: 'Market Correction', category: 'markets', emoji: '📉',
    definition: 'A short-term drop in the stock market of 10% or more to "correct" overvalued prices.',
    example: 'Letting a little air out of a balloon that got too big.',
  },
  {
    id: 'short-selling', term: 'Short Selling', category: 'basics', emoji: '📉',
    definition: 'Borrowing a stock and selling it, hoping to buy it back later at a lower price for a profit.',
    example: 'Betting that a team will lose.',
  },

  // NUMBERS & METRICS (61-80)
  {
    id: 'market-cap', term: 'Market Cap', category: 'numbers', emoji: '🏷️',
    definition: 'The total value of all of a company\'s outstanding shares.',
    example: 'The "sticker price" of the entire company.',
  },
  {
    id: 'pe-ratio', term: 'P/E Ratio', category: 'numbers', emoji: '⚖️',
    definition: 'Price-to-Earnings Ratio — Measures a company\'s current share price relative to its per-share earnings.',
    example: 'How much investors pay for $1 of profit.',
    imageUrl: 'https://www.corporatefinanceinstitute.com/assets/images/cfi/pe-ratio-formula.png',
  },
  {
    id: 'eps', term: 'EPS', category: 'numbers', emoji: '💵',
    definition: 'Earnings Per Share — The portion of a company\'s profit allocated to each outstanding share of common stock.',
    example: 'If a pizza has 8 slices, EPS is the amount of pepperoni on each slice.',
  },
  {
    id: 'dividend-yield', term: 'Dividend Yield', category: 'numbers', emoji: '📊',
    definition: 'The percentage of a company\'s share price that it pays out as dividends each year.',
    example: 'The "interest rate" you get just for owning the stock.',
  },
  {
    id: 'beta', term: 'Beta', category: 'numbers', emoji: '🎢',
    definition: 'A measure of a stock\'s volatility in relation to the overall market.',
    example: 'How much more (or less) a car shakes compared to the road.',
  },
  {
    id: 'volume', term: 'Volume', category: 'numbers', emoji: '🔊',
    definition: 'The total number of shares of a stock traded during a specific period.',
    example: 'How crowded a store is. High volume = lots of activity.',
  },
  {
    id: 'revenue', term: 'Revenue', category: 'numbers', emoji: '💰',
    definition: 'The total amount of money a company brings in from sales before subtracting expenses.',
    example: 'Every dollar put into a cash register.',
  },
  {
    id: 'profit-margin', term: 'Profit Margin', category: 'numbers', emoji: '📈',
    definition: 'A percentage that shows how much of every dollar of sales a company actually keeps as profit.',
    example: 'How much juice you get from squeezing an orange.',
  },
  {
    id: 'roa', term: 'ROA', category: 'numbers', emoji: '🏗️',
    definition: 'Return on Assets — How profitable a company is relative to its total assets.',
    example: 'How hard your tools are working for you.',
  },
  {
    id: 'roe', term: 'ROE', category: 'numbers', emoji: '👑',
    definition: 'Return on Equity — Measures how much profit a company generates with the money shareholders have invested.',
    example: 'Efficiency of using the owner\'s money.',
  },

  // TRADING & STRATEGIES (81-100)
  {
    id: 'candlestick', term: 'Candlestick', category: 'basics', emoji: '🕯️',
    definition: 'A type of price chart used that displays the high, low, open, and closing prices of a security.',
    example: 'A "snapshot" of a stock\'s movement in a single minute or day.',
    detailedExample: 'Green candles (bullish) mean the price closed higher than it opened. Red candles (bearish) mean it closed lower. The "wick" shows how far the price went before coming back.',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Candlestick_chart_anatomy.png',
  },
  {
    id: 'order-limit', term: 'Limit Order', category: 'basics', emoji: '🛑',
    definition: 'An order to buy or sell a stock only at a specific price or better.',
    example: 'Setting a "max price" you\'re willing to pay at an auction.',
  },
  {
    id: 'order-market', term: 'Market Order', category: 'basics', emoji: '⚡',
    definition: 'An order to buy or sell a stock immediately at the best available current price.',
    example: 'Paying the price on the tag at a department store.',
  },
  {
    id: 'stop-loss', term: 'Stop Loss', category: 'basics', emoji: '🛡️',
    definition: 'An order placed with a broker to sell a security when it reaches a certain price to prevent further loss.',
    example: 'An "emergency brake" for your investment.',
  },
  {
    id: 'support-resistance', term: 'Support & Resistance', category: 'markets', emoji: '🧱',
    definition: 'Price levels that a stock has difficulty falling below (support) or rising above (resistance).',
    example: 'The "floor" and the "ceiling" of a price range.',
    imageUrl: 'https://www.priceaction.com/wp-content/uploads/2021/04/support-and-resistance-levels.png',
  },
  {
    id: 'rsi', term: 'RSI Indicator', category: 'numbers', emoji: '📉',
    definition: 'Relative Strength Index — A momentum indicator that measures the speed and change of price movements.',
    example: 'A speedometer that tells you if a stock is moving "too fast" (overbought) or "too slow" (oversold).',
    imageUrl: 'https://school.stockcharts.com/lib/exe/fetch.php?media=market_analysis:rsi:rsi-01.png',
  },
  {
    id: 'moving-average', term: 'Moving Average', category: 'numbers', emoji: '〰️',
    definition: 'A technical indicator that smooths out price data to help identify trends.',
    example: 'A "clean view" of a messy line.',
  },
  {
    id: 'short-squeeze', term: 'Short Squeeze', category: 'markets', emoji: '🍋',
    definition: 'A rapid increase in the price of a stock that forces short sellers to buy shares back, driving the price even higher.',
    example: 'A crowded room where everyone tries to run for the same small exit at once.',
  },
  {
    id: 'arbitrage', term: 'Arbitrage', category: 'markets', emoji: '💱',
    definition: 'Simultaneously buying and selling the same asset in different markets to profit from small price differences.',
    example: 'Buying a toy for $5 at a yard sale and selling it for $10 on eBay immediately.',
  },
  {
    id: 'options-contract', term: 'Options Contract', category: 'basics', emoji: '📑',
    definition: 'A contract that gives you the right (but not the obligation) to buy or sell a stock at a set price.',
    example: 'A coupon that lets you lock in today\'s price for a future purchase.',
  },
  {
    id: 'margin', term: 'Buying on Margin', category: 'basics', emoji: '🏦',
    definition: 'Borrowing money from a broker to purchase stock—using your existing stocks as collateral.',
    example: 'Using a credit card to buy a lottery ticket. High risk of losing more than you have.',
  },
  {
    id: 'day-trading', term: 'Day Trading', category: 'basics', emoji: '⏱️',
    definition: 'The practice of buying and selling a security within the same trading day.',
    example: 'Sneaker flipping but with digital assets and much faster.',
  },
  {
    id: 'swing-trading', term: 'Swing Trading', category: 'basics', emoji: '🌊',
    definition: 'A trading strategy that attempts to capture gains in a stock within one to several days.',
    example: 'Surfing the waves—you wait for the right move and ride it for a bit.',
  },
  {
    id: 'dollar-cost-averaging', term: 'DCA', category: 'basics', emoji: '📅',
    definition: 'Investing a fixed amount of money at regular intervals, regardless of the stock price.',
    example: 'Setting an "automatic subscription" for your investments.',
  },
  {
    id: 'blue-chip-index', term: 'Dow 30', category: 'markets', emoji: '🏭',
    definition: 'Refers to the Dow Jones Industrial Average—representing 30 of the most significant US stocks.',
    example: 'The "Hall of Fame" for the industrial world.',
  },
  {
    id: 'fiscal-year', term: 'Fiscal Year', category: 'numbers', emoji: '📆',
    definition: 'The 12-month period that a company or government uses for financial reporting and budgeting.',
    example: 'The "school year" for a company\'s money.',
  },
  {
    id: 'capital-gains', term: 'Capital Gains', category: 'basics', emoji: '📈',
    definition: 'The profit earned from the sale of an asset like a stock or property.',
    example: 'The "prize money" you get when you sell high.',
  },
  {
    id: 'portfolio-rebalancing', term: 'Rebalancing', category: 'basics', emoji: '⚖️',
    definition: 'Realignment of the weightings of a portfolio of assets to maintain original risk levels.',
    example: 'Cleaning up your messy room so you know where everything is.',
  },
  {
    id: 'fundamental-analysis', term: 'Fundamentals', category: 'basics', emoji: '🔍',
    definition: 'Evaluating a stock by examining its related economic, financial, and other qualitative and quantitative factors.',
    example: 'Checking the engine and tires before buying a car.',
  },
  {
    id: 'technical-analysis', term: 'Technical Analysis', category: 'basics', emoji: '📈',
    definition: 'Predicting future price movements based on historical price and volume data.',
    example: 'Predicting the weather based on past patterns.',
  },
  // ADDING MORE TO REACH 100...
  { id: 'accrued-interest', term: 'Accrued Interest', category: 'numbers', emoji: '⏳', definition: 'Interest that has been earned but not yet paid.', example: 'Like a wage you have earned but haven\'t received your paycheck for yet.' },
  { id: 'amortization', term: 'Amortization', category: 'numbers', emoji: '📅', definition: 'The process of spreading out a loan into a series of fixed payments over time.', example: 'Breaking down a huge debt into bite-sized monthly snacks.' },
  { id: 'annuity', term: 'Annuity', category: 'basics', emoji: '🔮', definition: 'A financial product that pays out a fixed stream of payments to an individual.', example: 'A "pension plan" you buy for yourself.' },
  { id: 'audit', term: 'Audit', category: 'basics', emoji: '🧐', definition: 'An official examination of an organization\'s accounts.', example: 'A financial "physical exam" performed by a doctor (accountant).' },
  { id: 'bear-trap', term: 'Bear Trap', category: 'markets', emoji: '🪤', definition: 'A false signal that a stock is heading down, when it is actually heading up.', example: 'A fake-out in basketball.' },
  { id: 'bull-trap', term: 'Bull Trap', category: 'markets', emoji: '🪤', definition: 'A false signal that a stock is heading up, when it is actually heading down.', example: 'Thinking you scored a goal only for it to be called offside.' },
  { id: 'capital', term: 'Capital', category: 'basics', emoji: '🏭', definition: 'The money or assets a person or company has to invest or run their business.', example: 'The "fuel" for a company\'s engine.' },
  { id: 'commodity', term: 'Commodity', category: 'markets', emoji: '⛽', definition: 'A basic good used in commerce that is interchangeable with others like oil, gold, or grains.', example: 'Energy or raw materials—generic things everyone needs.' },
  { id: 'correlation', term: 'Correlation', category: 'numbers', emoji: '🔗', definition: 'The relationship between how two different stocks or assets move in relation to each other.', example: 'If ice cream sales go up when it\'s hot, they are "correlated" with temperature.' },
  { id: 'custodian', term: 'Custodian', category: 'basics', emoji: '🔒', definition: 'A financial institution that holds a customer\’s securities for safekeeping to minimize risk of theft or loss.', example: 'A digital bodyguard for your stocks.' },
  { id: 'dead-cat-bounce', term: 'Dead Cat Bounce', category: 'markets', emoji: '🐱', definition: 'A temporary recovery in share prices after a substantial fall, caused by speculators buying to cover their positions.', example: 'If you drop a dead cat from a skyscraper, it might bounce a little, but it\'s still dead.' },
  { id: 'default', term: 'Default', category: 'basics', emoji: '❌', definition: 'Failure to repay a debt according to the agreed-upon terms.', example: 'Breaking a promise to pay back a loan.' },
  { id: 'deflation', term: 'Deflation', category: 'markets', emoji: '🧊', definition: 'When prices for goods and services fall, often caused by a decrease in the supply of money.', example: 'The opposite of inflation—your money buys MORE over time (sounds good, but usually means a bad economy).' },
  { id: 'derivative', term: 'Derivative', category: 'basics', emoji: '🌿', definition: 'A financial contract that gets its value from an underlying asset like a stock or commodity.', example: 'Jam is a "derivative" of fruit. If fruit prices go up, jam prices go up.' },
  { id: 'equities', term: 'Equities', category: 'stocks', emoji: '⚖️', definition: 'Another word for stocks or shares of a company.', example: 'An equity = a piece of the pie.' },
  { id: 'escrow', term: 'Escrow', category: 'basics', emoji: '📥', definition: 'A neutral third party holding assets or money during a transaction until certain conditions are met.', example: 'A referee holding the trophy until the game is over.' },
  { id: 'expense-ratio', term: 'Expense Ratio', category: 'numbers', emoji: '✂️', definition: 'The annual fee that all funds (like ETFs or mutual funds) charge their shareholders.', example: 'The "subscription fee" for owning a fund.' },
  { id: 'fed', term: 'The Fed', category: 'markets', emoji: '🏛️', definition: 'The Federal Reserve—the central bank of the United States that sets interest rates.', example: 'The "manager" of the US money supply.' },
  { id: 'fiduciary', term: 'Fiduciary', category: 'basics', emoji: '🤝', definition: 'A person or organization that is legally required to act in the best interest of another person.', example: 'A professional who promises to help you, not just themselves.' },
  { id: 'fixed-income', term: 'Fixed Income', category: 'basics', emoji: '📅', definition: 'Investments like bonds that pay a fixed amount of interest regularly.', example: 'Getting a "salary" from your investments instead of waiting for a price jump.' },
  { id: 'fomc', term: 'FOMC', category: 'markets', emoji: '🗳️', definition: 'The Federal Open Market Committee—the part of the Fed that makes decisions about interest rates.', example: 'The "jury" that decides how expensive borrowing money will be.' },
  { id: 'gap', term: 'Market Gap', category: 'markets', emoji: '🕳️', definition: 'When a stock price opens much higher or lower than its previous close with no trading in between.', example: 'Teleportation—the price skipped a few steps.' },
  { id: 'hedge', term: 'Hedge', category: 'basics', emoji: '⚔️', definition: 'An investment made to reduce the risk of adverse price movements in an asset.', example: 'Buying "insurance" for your investments.' },
  { id: 'holding-period', term: 'Holding Period', category: 'basics', emoji: '⏳', definition: 'The amount of time you keep an investment before selling it.', example: 'How long you stay at the party.' },
  { id: 'incumbebt', term: 'Incumbent', category: 'basics', emoji: '🏰', definition: 'An established company that holds a large market share in its industry.', example: 'The "king of the hill" that new startups try to dethrone.' },
  { id: 'insider-trading', term: 'Insider Trading', category: 'basics', emoji: '🤫', definition: 'Trading a stock based on information that is not yet public. Illegal.', example: 'Cheating by looking at the answer key before the test.' },
  { id: 'leverage', term: 'Leverage', category: 'basics', emoji: '🏗️', definition: 'Using borrowed money to increase the potential return of an investment.', example: 'Using a seesaw to lift something much heavier than you.' },
  { id: 'margin-call', term: 'Margin Call', category: 'basics', emoji: '📞', definition: 'When your broker demands you add more money to your account because your investments fell too far.', example: 'The bank calling to say "pay up now or lose everything."' },
  { id: 'market-depth', term: 'Market Depth', category: 'markets', emoji: '🌊', definition: 'The market\'s ability to handle large orders without significantly changing the price.', example: 'How deep the pool is—a large splash matters less in a deep pool.' },
  { id: 'market-order', term: 'Market Order', category: 'basics', emoji: '⚡', definition: 'An order to buy or sell a stock immediately at the current market price.', example: 'Using "Buy It Now" on eBay.' },
  { id: 'maturity-date', term: 'Maturity Date', category: 'basics', emoji: '🏁', definition: 'The date on which a bond must be repaid in full to the investor.', example: 'The "finish line" of a loan.' },
  { id: 'moving-average', term: 'Moving Average', category: 'numbers', emoji: '〰️', definition: 'An indicator that smooths out price trends by filtering out the "noise" from random price fluctuations.', example: 'Squinting your eyes to see the main shape of a messy line.' },
  { id: 'odd-lot', term: 'Odd Lot', category: 'stocks', emoji: '🧩', definition: 'An amount of stock that is less than a standard unit of trading (usually 100 shares).', example: 'Buying a single cookie instead of a whole box.' },
  { id: 'over-the-counter', term: 'OTC', category: 'markets', emoji: '🏪', definition: 'Stocks traded through a dealer network rather than on a centralized exchange like the NYSE.', example: 'Buying from a street vendor instead of a big mall.' },
  { id: 'peg-ratio', term: 'PEG Ratio', category: 'numbers', emoji: '📏', definition: 'Price/Earnings to Growth ratio—helps determine if a stock is overvalued or undervalued based on its growth.', example: 'A more accurate ruler for measuring value.' },
  { id: 'rally', term: 'Market Rally', category: 'markets', emoji: '📈', definition: 'A period of sustained increase in the prices of stocks, bonds, or related indexes.', example: 'A team going on a scoring streak.' },
  { id: 'return', term: 'ROI', category: 'numbers', emoji: '🏅', definition: 'Return on Investment—The profit or loss made on an investment relative to its cost.', example: 'Your "reward" for the risk you took.' },
  { id: 'scarcity', term: 'Scarcity', category: 'basics', emoji: '💎', definition: 'When high demand meets limited supply, driving prices up.', example: 'Only 10 tickets left for a concert everyone wants to see.' },
  { id: 'sec', term: 'SEC', category: 'markets', emoji: '👮', definition: 'The Securities and Exchange Commission—the government agency that protects investors and maintains fair markets.', example: 'The "police" of the stock market.' },
  { id: 'sector-rotation', term: 'Sector Rotation', category: 'markets', emoji: '🔄', definition: 'When investors move money from one industry (like Tech) to another (like Energy) based on economic trends.', example: 'Moving from the shallow end to the deep end of the pool.' },
  { id: 'slump', term: 'Market Slump', category: 'markets', emoji: '💤', definition: 'A period where stock prices or economic activity decline or remain stagnant.', example: 'A "cold streak" for the market.' },
  { id: 'speculation', term: 'Speculation', category: 'basics', emoji: '🎲', definition: 'Investing in high-risk assets with the hope of a quick profit.', example: 'Gambling on a "hunch" instead of facts.' },
  { id: 'spread', term: 'Bid-Ask Spread', category: 'markets', emoji: '↔️', definition: 'The difference between the highest price a buyer will pay (bid) and the lowest price a seller will accept (ask).', example: 'The "gap" during a negotiation.' },
  { id: 'stagnation', term: 'Stagnation', category: 'markets', emoji: '🛑', definition: 'A period of little to no economic growth.', example: 'Water that isn\'t moving—it just sits there.' },
  { id: 'ticker', term: 'Ticker', category: 'markets', emoji: '📡', definition: 'The scrolling display that shows real-time stock prices and trading activity.', example: 'The "live scoreboard" of the market.' },
  { id: 'undervalued', term: 'Undervalued', category: 'basics', emoji: '🎁', definition: 'A stock that is trading below its true actual value.', example: 'Finding a designer shirt at a garage sale for $1.' },
  { id: 'venture-capital', term: 'Venture Capital', category: 'basics', emoji: '🏢', definition: 'Money provided by investors to startups and small businesses with long-term growth potential.', example: 'Shark Tank—rich people giving money to new ideas.' },
  { id: 'wash-sale', term: 'Wash Sale', category: 'basics', emoji: '🧼', definition: 'Selling a stock at a loss and buying it right back just to get a tax benefit. Illegal if done within 30 days.', example: 'Trying to trick the system to pay fewer taxes.' },
  { id: 'whale', term: 'Whale', category: 'basics', emoji: '🐋', definition: 'An investor with so much money that their trades can move the entire market.', example: 'A giant jumping into a small pool—everyone feels the wave.' },
  { id: 'yield-curve', term: 'Yield Curve', category: 'numbers', emoji: '📉', definition: 'A line that plots the interest rates of bonds with different maturity dates.', example: 'A "crystal ball" that helps predict future recessions.' },
]
