import type { GlossaryTerm, StudyModule } from './types'

export const studyModules: StudyModule[] = [
  {
    id: 'reading-stock-page',
    title: 'Reading a Stock Page',
    level: 'Start here',
    minutes: 8,
    description: 'Study the order to read a company page so prices, charts, news, and filings feel connected.',
    goal: 'Leave with a simple research routine you can repeat on any ticker.',
    video: {
      youtubeId: 'p7HKvqRI_Bo',
      title: 'How does the stock market work?',
      channel: 'TED-Ed',
      sourceUrl: 'https://www.youtube.com/watch?v=p7HKvqRI_Bo',
    },
    terms: ['stock', 'ticker-symbol', 'market-cap', 'volume'],
    steps: [
      {
        title: 'Start with the business',
        body: 'Before the chart, ask what the company sells, who buys it, and how it makes money.',
        example: 'For Apple, the business includes iPhones, Macs, services, and subscriptions.',
        takeaway: 'A price move makes more sense when you know what the business actually does.',
      },
      {
        title: 'Read the price move in context',
        body: 'A stock being up or down today is only one clue. Compare it with the 52-week high, 52-week low, and recent news.',
        example: 'A 3 percent drop may be small if the stock doubled this year, but large if the company also missed earnings.',
        takeaway: 'Always ask what changed, not just whether the price moved.',
      },
      {
        title: 'Connect the sources',
        body: 'Use news for the event, filings for official company facts, and notes for your own questions.',
        example: 'If a headline says sales slowed, check the latest 10-Q or earnings report for revenue and guidance.',
        takeaway: 'Good research compares sources instead of trusting one headline.',
      },
    ],
    quickCheck: {
      question: 'What should you check before reacting to a price move?',
      choices: ['Only today price', 'The business, chart, news, and filings', 'Only social media posts'],
      answer: 'The business, chart, news, and filings',
      explanation: 'A stock move needs context. The business, chart, news, and filings help explain what changed.',
    },
  },
  {
    id: 'key-stats',
    title: 'Key Stats',
    level: 'Core skill',
    minutes: 10,
    description: 'Decode market cap, P/E, EPS, volume, and yearly ranges without memorizing finance jargon.',
    goal: 'Understand what each number can tell you and what it cannot tell you by itself.',
    video: {
      youtubeId: 'cppxO67e6eo',
      title: 'Introduction to the Price-to-Earnings Ratio',
      channel: 'Khan Academy',
      sourceUrl: 'https://www.youtube.com/watch?v=cppxO67e6eo',
    },
    terms: ['market-cap', 'pe-ratio', 'eps', 'volume'],
    steps: [
      {
        title: 'Use market cap for size',
        body: 'Market cap estimates the total stock market value of a company.',
        example: 'A company worth $2 trillion is usually more stable than a tiny company, but it may also grow more slowly.',
        takeaway: 'Market cap tells you size, not whether the stock is cheap or expensive.',
      },
      {
        title: 'Use P/E to compare price and profit',
        body: 'P/E shows how much investors pay for each dollar of company profit.',
        example: 'A P/E of 30 means investors pay about $30 for $1 of yearly earnings.',
        takeaway: 'High P/E can mean growth hopes, but it can also mean the price is stretched.',
      },
      {
        title: 'Use EPS and volume for signal',
        body: 'EPS shows profit per share. Volume shows how many shares are trading.',
        example: 'Rising EPS with heavy volume can mean investors are paying attention to new information.',
        takeaway: 'Numbers work best when you compare them together.',
      },
    ],
    quickCheck: {
      question: 'What does P/E compare?',
      choices: ['Stock price and company profit', 'News stories and filings', 'Volume and market cap'],
      answer: 'Stock price and company profit',
      explanation: 'P/E compares the stock price with earnings, which are company profit per share.',
    },
  },
  {
    id: 'earnings',
    title: 'Earnings',
    level: 'Research habit',
    minutes: 9,
    description: 'Understand what earnings reports are and why stocks can move even when a company made money.',
    goal: 'Know how to read EPS, revenue, margins, and guidance like a student researcher.',
    video: {
      youtubeId: 'RouNXdkC0do',
      title: 'Earnings and EPS',
      channel: 'Khan Academy',
      sourceUrl: 'https://www.youtube.com/watch?v=RouNXdkC0do',
    },
    terms: ['eps', 'revenue', 'profit-margin', 'fiscal-year'],
    steps: [
      {
        title: 'Separate revenue from profit',
        body: 'Revenue is money from sales. Profit is what is left after costs.',
        example: 'A company can sell more products but still earn less if costs rise faster than sales.',
        takeaway: 'More sales do not always mean a stronger business.',
      },
      {
        title: 'Compare actual results with expectations',
        body: 'Stocks often react to whether the company beat or missed what analysts expected.',
        example: 'EPS of $2.10 can look strong, but if investors expected $2.40, the stock may fall.',
        takeaway: 'The market reacts to surprise, not just the raw number.',
      },
      {
        title: 'Watch guidance',
        body: 'Guidance is what management says about the future.',
        example: 'If a company says next quarter may be slower, investors may care more about that than last quarter.',
        takeaway: 'Future expectations can move prices more than past results.',
      },
    ],
    quickCheck: {
      question: 'Why can a stock fall after the company reports a profit?',
      choices: ['Profit is always bad', 'Results or guidance may be worse than expected', 'Filings are not important'],
      answer: 'Results or guidance may be worse than expected',
      explanation: 'Investors compare results with expectations and listen closely to guidance about the future.',
    },
  },
  {
    id: 'sec-filings',
    title: 'SEC Filings',
    level: 'Official sources',
    minutes: 11,
    description: 'Study the common filing types so official company documents feel less confusing.',
    goal: 'Know where to look for annual facts, quarterly updates, major events, and voting details.',
    video: {
      youtubeId: 'hi-Ua4JBGmA',
      title: 'How to Read a 10-K Annual Report',
      channel: 'YouTube lesson',
      sourceUrl: 'https://www.youtube.com/watch?v=hi-Ua4JBGmA',
    },
    terms: ['sec', 'fiscal-year', 'audit', 'insider-trading'],
    steps: [
      {
        title: 'Use 10-K for the full yearly story',
        body: 'A 10-K is the annual report. It covers the business, risks, financial statements, and management discussion.',
        example: 'If you want to know the biggest risks a company lists for itself, start with the 10-K.',
        takeaway: 'The 10-K is slower to read, but it is one of the most complete sources.',
      },
      {
        title: 'Use 10-Q for quarterly updates',
        body: 'A 10-Q is a shorter quarterly report that updates sales, profit, cash, and risks.',
        example: 'If a headline says demand changed this quarter, the 10-Q can show the numbers behind it.',
        takeaway: 'The 10-Q helps you check whether the story is showing up in the results.',
      },
      {
        title: 'Use 8-K and proxy filings for events',
        body: 'An 8-K reports major events. A proxy filing explains voting, board details, and executive pay.',
        example: 'A new CEO, big deal, or major company update often appears in an 8-K.',
        takeaway: 'Different filing types answer different research questions.',
      },
    ],
    quickCheck: {
      question: 'Which filing is usually the annual report?',
      choices: ['10-K', '8-K', 'DEF 14A'],
      answer: '10-K',
      explanation: 'A 10-K is the full annual report. A 10-Q is quarterly, and an 8-K covers major events.',
    },
  },
  {
    id: 'news',
    title: 'Market News',
    level: 'Source reading',
    minutes: 8,
    description: 'Read headlines without getting pulled into panic, hype, or one-sided stories.',
    goal: 'Turn a headline into a clear question you can verify with data.',
    video: {
      youtubeId: 'EAKGuN-d07Q',
      title: 'Stock Market Terms for Beginners',
      channel: 'YouTube lesson',
      sourceUrl: 'https://www.youtube.com/watch?v=EAKGuN-d07Q',
    },
    terms: ['ticker-symbol', 'sector-rotation', 'volatility', 'revenue'],
    steps: [
      {
        title: 'Find the actual event',
        body: 'Separate what happened from how people reacted.',
        example: 'A headline may say a stock plunged, but the event might be lower guidance or a missed profit target.',
        takeaway: 'The event matters more than the dramatic wording.',
      },
      {
        title: 'Check if it is company-specific or market-wide',
        body: 'A stock can move because of its own news or because the whole sector is moving.',
        example: 'A chip stock may rise because its earnings were strong or because the entire semiconductor group is rising.',
        takeaway: 'Compare the company with peers before deciding what the headline means.',
      },
      {
        title: 'Write one question',
        body: 'Turn every story into one research question.',
        example: 'If layoffs are announced, ask whether revenue is slowing, costs are too high, or margins are under pressure.',
        takeaway: 'A good question is more useful than a fast opinion.',
      },
    ],
    quickCheck: {
      question: 'What is the best first move after reading a dramatic headline?',
      choices: ['React fast', 'Find the event and verify it', 'Ignore all news'],
      answer: 'Find the event and verify it',
      explanation: 'A headline is a starting point. The next step is checking the event against data and official sources.',
    },
  },
  {
    id: 'watchlist',
    title: 'Building a Watchlist',
    level: 'Daily routine',
    minutes: 7,
    description: 'Use a watchlist as a study queue, not just a list of prices.',
    goal: 'Save companies with a reason, track key words, and update your notes over time.',
    video: {
      youtubeId: 'p7HKvqRI_Bo',
      title: 'How does the stock market work?',
      channel: 'TED-Ed',
      sourceUrl: 'https://www.youtube.com/watch?v=p7HKvqRI_Bo',
    },
    terms: ['ticker-symbol', 'sector-rotation', 'volume', 'support-resistance'],
    steps: [
      {
        title: 'Save with a reason',
        body: 'Every ticker should have a reason it belongs on your list.',
        example: 'A reason could be new product cycle, earnings next week, falling margins, or a sector you want to study.',
        takeaway: 'A watchlist is stronger when every ticker has a question attached.',
      },
      {
        title: 'Track the words that matter',
        body: 'Keyword alerts help you notice repeated themes in news and filings.',
        example: 'Words like margin, guidance, debt, demand, and inventory can point to important changes.',
        takeaway: 'Repeated words often reveal the real story behind the price.',
      },
      {
        title: 'Review, then update your view',
        body: 'Use notes to write what you believed and what new data changed.',
        example: 'If your note said demand is strong, update it when the next report shows weaker sales.',
        takeaway: 'Good research changes when the facts change.',
      },
    ],
    quickCheck: {
      question: 'What makes a watchlist useful for studying?',
      choices: ['Saving random tickers', 'Saving tickers with questions and notes', 'Only checking the price once'],
      answer: 'Saving tickers with questions and notes',
      explanation: 'A study watchlist connects tickers to questions, sources, notes, and future checks.',
    },
  },
  {
    id: 'charts-candles',
    title: 'Reading Charts',
    level: 'Chart basics',
    minutes: 9,
    description: 'Learn what a chart can show, what it cannot prove, and how candles, ranges, and volume work together.',
    goal: 'Use charts as context, not as a magic prediction tool.',
    video: {
      youtubeId: 'EAKGuN-d07Q',
      title: 'Stock Market Terms for Beginners',
      channel: 'YouTube lesson',
      sourceUrl: 'https://www.youtube.com/watch?v=EAKGuN-d07Q',
    },
    terms: ['candlestick', 'volume', 'moving-average', 'support-resistance'],
    steps: [
      {
        title: 'Read the time frame first',
        body: 'A one-day chart and a one-year chart can tell very different stories about the same stock.',
        example: 'A stock may look weak today but still be in a strong long-term uptrend.',
        takeaway: 'Never judge a chart without checking the time frame.',
      },
      {
        title: 'Use candles for range',
        body: 'A candle shows where price opened, closed, and how far it moved during that period.',
        example: 'A tall candle can show a big reaction after earnings or major news.',
        takeaway: 'Candles show movement, but they do not explain the reason by themselves.',
      },
      {
        title: 'Compare price with volume',
        body: 'Volume helps you see whether many investors joined the move or only a few trades caused it.',
        example: 'A breakout on heavy volume usually matters more than a breakout on quiet trading.',
        takeaway: 'Price plus volume gives a stronger clue than price alone.',
      },
    ],
    quickCheck: {
      question: 'Why should you check the chart time frame first?',
      choices: ['It changes the story you see', 'It guarantees the next price', 'It replaces all company research'],
      answer: 'It changes the story you see',
      explanation: 'Different time frames can make the same stock look short-term weak or long-term strong.',
    },
  },
  {
    id: 'indexes-benchmarks',
    title: 'Indexes and Benchmarks',
    level: 'Market map',
    minutes: 8,
    description: 'Understand the S&P 500, Nasdaq, Dow, and why investors compare single stocks with a benchmark.',
    goal: 'Know whether a company is moving alone or with the broader market.',
    video: {
      youtubeId: 'p7HKvqRI_Bo',
      title: 'How does the stock market work?',
      channel: 'TED-Ed',
      sourceUrl: 'https://www.youtube.com/watch?v=p7HKvqRI_Bo',
    },
    terms: ['index', 'sp500', 'nasdaq-composite', 'dow-jones'],
    steps: [
      {
        title: 'Use indexes as scoreboards',
        body: 'An index tracks a group of stocks so you can see what a market area is doing.',
        example: 'The S&P 500 gives a broad view of large US companies.',
        takeaway: 'An index helps you compare one stock with the wider market.',
      },
      {
        title: 'Match the benchmark',
        body: 'A tech stock is often compared with Nasdaq, while a large mixed company may be compared with the S&P 500.',
        example: 'If Apple falls less than Nasdaq on a rough tech day, it may be holding up better than peers.',
        takeaway: 'The right benchmark makes comparisons fairer.',
      },
      {
        title: 'Ask what is leading',
        body: 'Sometimes a few huge companies can pull an index up or down.',
        example: 'Large tech companies can strongly affect Nasdaq because they carry big weight.',
        takeaway: 'Index moves still need context about which companies are leading.',
      },
    ],
    quickCheck: {
      question: 'What is a benchmark useful for?',
      choices: ['Comparing a stock with a market group', 'Guaranteeing a profit', 'Replacing a company page'],
      answer: 'Comparing a stock with a market group',
      explanation: 'A benchmark helps you see whether a stock is moving differently from a similar group.',
    },
  },
  {
    id: 'etfs-diversification',
    title: 'ETFs and Diversification',
    level: 'Portfolio basics',
    minutes: 10,
    description: 'Learn how ETFs bundle many investments and why diversification can lower single-company risk.',
    goal: 'Understand why many investors study baskets, not only individual tickers.',
    video: {
      youtubeId: 'EAKGuN-d07Q',
      title: 'Stock Market Terms for Beginners',
      channel: 'YouTube lesson',
      sourceUrl: 'https://www.youtube.com/watch?v=EAKGuN-d07Q',
    },
    terms: ['etf', 'diversification', 'index', 'expense-ratio'],
    steps: [
      {
        title: 'Know what the basket owns',
        body: 'An ETF can hold hundreds of stocks, bonds, or other assets in one ticker.',
        example: 'An S&P 500 ETF gives exposure to many large US companies at once.',
        takeaway: 'An ETF is only as good as what is inside the basket.',
      },
      {
        title: 'Use diversification to reduce one-stock risk',
        body: 'If one company has a bad quarter, a diversified basket may be less affected.',
        example: 'One weak retailer matters less inside a broad market ETF than in a one-stock portfolio.',
        takeaway: 'Diversification lowers company-specific risk, but it does not remove all risk.',
      },
      {
        title: 'Check the fee',
        body: 'Expense ratio is the yearly cost of owning a fund.',
        example: 'A 0.03 percent expense ratio is much cheaper than a 1 percent expense ratio.',
        takeaway: 'Fees look small, but they matter over long periods.',
      },
    ],
    quickCheck: {
      question: 'What does diversification mainly help reduce?',
      choices: ['One-company risk', 'All possible risk', 'The need to read anything'],
      answer: 'One-company risk',
      explanation: 'Diversification spreads exposure so one company has less control over the full result.',
    },
  },
  {
    id: 'dividends-income',
    title: 'Dividends and Yield',
    level: 'Income basics',
    minutes: 8,
    description: 'Study how dividends work, why yield can be useful, and why a high yield can also be a warning sign.',
    goal: 'Read dividend information without assuming higher always means better.',
    video: {
      youtubeId: 'EAKGuN-d07Q',
      title: 'Stock Market Terms for Beginners',
      channel: 'YouTube lesson',
      sourceUrl: 'https://www.youtube.com/watch?v=EAKGuN-d07Q',
    },
    terms: ['dividend', 'dividend-yield', 'profit-margin', 'blue-chip'],
    steps: [
      {
        title: 'Separate payment from price move',
        body: 'A dividend is cash paid to shareholders, while the stock price can still rise or fall.',
        example: 'A company may pay a dividend but lose stock value if the business weakens.',
        takeaway: 'Dividend income is only one part of total return.',
      },
      {
        title: 'Ask if the dividend is covered',
        body: 'A company needs enough profit and cash to keep paying dividends.',
        example: 'If profit drops for several quarters, management may cut the dividend.',
        takeaway: 'A dividend is stronger when the business can afford it.',
      },
      {
        title: 'Watch very high yield',
        body: 'A high yield can happen because the price fell, not because the company became safer.',
        example: 'If a stock drops from $100 to $50, the yield may jump even if risk rose.',
        takeaway: 'High yield can be attractive, but it can also signal trouble.',
      },
    ],
    quickCheck: {
      question: 'Why can a very high dividend yield be risky?',
      choices: ['The stock price may have fallen for a bad reason', 'It means the company cannot have revenue', 'It always means fast growth'],
      answer: 'The stock price may have fallen for a bad reason',
      explanation: 'Yield rises when price falls, so a high yield can reflect investor concern.',
    },
  },
  {
    id: 'bull-bear-cycles',
    title: 'Bull, Bear, and Corrections',
    level: 'Market cycles',
    minutes: 8,
    description: 'Learn the language of rising markets, falling markets, pullbacks, and how to stay calm around big moves.',
    goal: 'Tell the difference between a normal pullback and a deeper market cycle.',
    video: {
      youtubeId: 'EAKGuN-d07Q',
      title: 'Stock Market Terms for Beginners',
      channel: 'YouTube lesson',
      sourceUrl: 'https://www.youtube.com/watch?v=EAKGuN-d07Q',
    },
    terms: ['bull-market', 'bear-market', 'correction', 'volatility'],
    steps: [
      {
        title: 'Name the market environment',
        body: 'Bull markets rise over time. Bear markets fall deeply and can last longer than a quick dip.',
        example: 'A broad 20 percent drop is usually treated differently from a 3 percent rough week.',
        takeaway: 'The market environment changes how investors read news.',
      },
      {
        title: 'Treat corrections as resets',
        body: 'A correction is a drop of about 10 percent or more from a recent high.',
        example: 'A correction can happen even inside a long-term bull market.',
        takeaway: 'Corrections are uncomfortable, but they are not always the end of a trend.',
      },
      {
        title: 'Use facts during fear',
        body: 'Big market moves can make headlines emotional, so check data and sources.',
        example: 'Compare index moves, earnings, interest rates, and company updates before reacting.',
        takeaway: 'Market labels help, but sources still matter most.',
      },
    ],
    quickCheck: {
      question: 'What is a market correction usually describing?',
      choices: ['A drop of about 10 percent or more', 'A guaranteed crash', 'A company changing its ticker'],
      answer: 'A drop of about 10 percent or more',
      explanation: 'A correction is a meaningful pullback from a recent high, but it does not always become a bear market.',
    },
  },
  {
    id: 'risk-volatility-beta',
    title: 'Risk, Volatility, and Beta',
    level: 'Risk reading',
    minutes: 9,
    description: 'Understand why some stocks move more than others and how beta helps compare a stock with the market.',
    goal: 'Explain risk in plain words instead of only saying a stock is scary or safe.',
    video: {
      youtubeId: 'EAKGuN-d07Q',
      title: 'Stock Market Terms for Beginners',
      channel: 'YouTube lesson',
      sourceUrl: 'https://www.youtube.com/watch?v=EAKGuN-d07Q',
    },
    terms: ['volatility', 'beta', 'liquidity', 'correlation'],
    steps: [
      {
        title: 'Separate movement from danger',
        body: 'Volatility means price moves around a lot. It can create risk, but it is not the same as the company being bad.',
        example: 'A young growth stock may swing more than a large stable company.',
        takeaway: 'Volatility describes the ride, not the whole business quality.',
      },
      {
        title: 'Use beta for market sensitivity',
        body: 'Beta compares how much a stock tends to move compared with the overall market.',
        example: 'A beta above 1 usually means the stock moves more than the market.',
        takeaway: 'Beta helps you estimate how jumpy a stock may be compared with the market.',
      },
      {
        title: 'Check liquidity',
        body: 'Liquid stocks are easier to buy or sell without a big price change.',
        example: 'A popular large-cap stock usually has more liquidity than a tiny penny stock.',
        takeaway: 'Low liquidity can make price moves more extreme.',
      },
    ],
    quickCheck: {
      question: 'What does beta compare?',
      choices: ['A stock movement with the overall market', 'A company revenue with its logo', 'A dividend with a filing date'],
      answer: 'A stock movement with the overall market',
      explanation: 'Beta helps show how sensitive a stock has been to market moves.',
    },
  },
  {
    id: 'order-types',
    title: 'Market, Limit, and Stop Orders',
    level: 'Trading tools',
    minutes: 9,
    description: 'Learn common order types so students understand how buying and selling instructions work.',
    goal: 'Know the difference between speed, price control, and risk controls.',
    video: {
      youtubeId: 'EAKGuN-d07Q',
      title: 'Stock Market Terms for Beginners',
      channel: 'YouTube lesson',
      sourceUrl: 'https://www.youtube.com/watch?v=EAKGuN-d07Q',
    },
    terms: ['market-order', 'order-limit', 'stop-loss', 'spread'],
    steps: [
      {
        title: 'Use market orders for speed',
        body: 'A market order tries to buy or sell right away at the best available price.',
        example: 'It is like saying, buy this now at the current checkout price.',
        takeaway: 'Market orders are fast, but the final price can change in a moving market.',
      },
      {
        title: 'Use limit orders for price control',
        body: 'A limit order only fills at your chosen price or better.',
        example: 'If you set a buy limit at $50, it will not buy above $50.',
        takeaway: 'Limit orders control price, but they may not fill.',
      },
      {
        title: 'Understand stop loss limits',
        body: 'A stop loss can help manage downside, but it does not guarantee a perfect exit price.',
        example: 'In a fast drop, the sale may happen below the stop price.',
        takeaway: 'Order tools help manage risk, but they do not remove risk.',
      },
    ],
    quickCheck: {
      question: 'What is the tradeoff with a limit order?',
      choices: ['More price control, but it may not fill', 'Guaranteed profit', 'No need to know the ticker'],
      answer: 'More price control, but it may not fill',
      explanation: 'A limit order protects the price, but the market may never reach that price.',
    },
  },
  {
    id: 'technical-tools',
    title: 'Moving Averages and RSI',
    level: 'Chart tools',
    minutes: 10,
    description: 'Study simple technical tools without treating them like crystal balls.',
    goal: 'Use indicators as questions to check, not as automatic answers.',
    video: {
      youtubeId: 'EAKGuN-d07Q',
      title: 'Stock Market Terms for Beginners',
      channel: 'YouTube lesson',
      sourceUrl: 'https://www.youtube.com/watch?v=EAKGuN-d07Q',
    },
    terms: ['moving-average', 'rsi', 'technical-analysis', 'support-resistance'],
    steps: [
      {
        title: 'Use moving averages to smooth noise',
        body: 'A moving average shows a cleaner trend line by averaging prices over time.',
        example: 'A 50-day moving average can show the medium-term trend better than one messy day.',
        takeaway: 'Moving averages help show trend direction, not certain future moves.',
      },
      {
        title: 'Use RSI as a speed check',
        body: 'RSI tries to show whether a move may be stretched after fast buying or selling.',
        example: 'A high RSI can suggest buyers moved quickly, but it does not mean the stock must fall.',
        takeaway: 'RSI is a clue, not a command.',
      },
      {
        title: 'Confirm with company facts',
        body: 'Technical tools are stronger when checked against earnings, news, and filings.',
        example: 'A chart breakout after strong earnings means more than a breakout with no clear event.',
        takeaway: 'Charts should start research, not end it.',
      },
    ],
    quickCheck: {
      question: 'How should students use chart indicators?',
      choices: ['As clues to investigate', 'As guaranteed answers', 'As a replacement for news and filings'],
      answer: 'As clues to investigate',
      explanation: 'Indicators can point to useful questions, but they need real-world context.',
    },
  },
  {
    id: 'fundamental-vs-technical',
    title: 'Fundamental vs. Technical Research',
    level: 'Research styles',
    minutes: 9,
    description: 'Compare business-based research with chart-based research and learn when each is useful.',
    goal: 'Build a balanced research routine instead of arguing that one tool is always right.',
    video: {
      youtubeId: 'p7HKvqRI_Bo',
      title: 'How does the stock market work?',
      channel: 'TED-Ed',
      sourceUrl: 'https://www.youtube.com/watch?v=p7HKvqRI_Bo',
    },
    terms: ['fundamental-analysis', 'technical-analysis', 'revenue', 'profit-margin'],
    steps: [
      {
        title: 'Use fundamentals for the business',
        body: 'Fundamental research asks whether the company is growing, profitable, and financially strong.',
        example: 'Revenue growth, margins, and cash flow are business clues.',
        takeaway: 'Fundamentals help explain what the company is becoming.',
      },
      {
        title: 'Use technicals for behavior',
        body: 'Technical research studies price and volume to understand how investors are trading.',
        example: 'A stock near support may show where buyers recently stepped in.',
        takeaway: 'Technicals help explain market behavior around the stock.',
      },
      {
        title: 'Combine both carefully',
        body: 'A strong business can still have a weak chart, and a strong chart can still belong to a risky business.',
        example: 'A stock may rally on hype even if profits are falling.',
        takeaway: 'Good research checks both the business and the market reaction.',
      },
    ],
    quickCheck: {
      question: 'What does fundamental research mainly study?',
      choices: ['The business and its numbers', 'Only candle colors', 'Only social media posts'],
      answer: 'The business and its numbers',
      explanation: 'Fundamental research focuses on company facts like sales, profit, and financial strength.',
    },
  },
  {
    id: 'valuation-growth-value',
    title: 'Valuation: Growth vs. Value',
    level: 'Valuation',
    minutes: 10,
    description: 'Learn why expensive-looking stocks can keep rising and cheap-looking stocks can stay cheap.',
    goal: 'Compare price, earnings, and growth expectations without oversimplifying.',
    video: {
      youtubeId: 'cppxO67e6eo',
      title: 'Introduction to the Price-to-Earnings Ratio',
      channel: 'Khan Academy',
      sourceUrl: 'https://www.youtube.com/watch?v=cppxO67e6eo',
    },
    terms: ['growth-stock', 'value-stock', 'pe-ratio', 'peg-ratio'],
    steps: [
      {
        title: 'Know what growth investors pay for',
        body: 'Growth investors often accept higher valuations because they expect faster future earnings.',
        example: 'A software company may trade at a high P/E if investors expect years of fast growth.',
        takeaway: 'High valuation can reflect high expectations.',
      },
      {
        title: 'Know why value can look cheap',
        body: 'A low valuation may mean the market sees slower growth or higher risk.',
        example: 'A retailer with falling sales may have a low P/E for a reason.',
        takeaway: 'Cheap is not the same as good.',
      },
      {
        title: 'Compare valuation with growth',
        body: 'PEG ratio tries to compare P/E with expected growth.',
        example: 'A high P/E may look more reasonable if earnings are growing quickly.',
        takeaway: 'Valuation makes more sense when paired with growth.',
      },
    ],
    quickCheck: {
      question: 'Why is a low P/E not always good?',
      choices: ['It may reflect weak growth or higher risk', 'It always means fraud', 'It means the company has no ticker'],
      answer: 'It may reflect weak growth or higher risk',
      explanation: 'A low P/E can be a bargain, but it can also mean investors expect trouble.',
    },
  },
  {
    id: 'sectors-rotation',
    title: 'Sectors and Rotation',
    level: 'Market map',
    minutes: 8,
    description: 'Learn how industries move differently and why money sometimes shifts from one sector to another.',
    goal: 'Understand whether a stock move is about the company, the sector, or the whole market.',
    video: {
      youtubeId: 'EAKGuN-d07Q',
      title: 'Stock Market Terms for Beginners',
      channel: 'YouTube lesson',
      sourceUrl: 'https://www.youtube.com/watch?v=EAKGuN-d07Q',
    },
    terms: ['sector-rotation', 'index', 'correlation', 'commodity'],
    steps: [
      {
        title: 'Group companies by industry',
        body: 'A sector is a group of companies with similar business drivers.',
        example: 'Banks, energy companies, and software companies can react to different news.',
        takeaway: 'Sector context helps explain why similar stocks move together.',
      },
      {
        title: 'Watch money rotate',
        body: 'Sector rotation happens when investors move money from one group to another.',
        example: 'Investors may favor energy when oil prices rise, then shift toward tech when growth hopes return.',
        takeaway: 'Rotation can move good companies even without company-specific news.',
      },
      {
        title: 'Compare with peers',
        body: 'Peer comparison shows whether one company is leading or just moving with the group.',
        example: 'If every bank stock falls, one bank may not have unique bad news.',
        takeaway: 'Always compare a stock with its sector peers.',
      },
    ],
    quickCheck: {
      question: 'What is sector rotation?',
      choices: ['Money moving between industry groups', 'A company changing its ticker', 'A stock split'],
      answer: 'Money moving between industry groups',
      explanation: 'Sector rotation describes investors shifting focus from one part of the market to another.',
    },
  },
  {
    id: 'fed-inflation-rates',
    title: 'The Fed, Inflation, and Rates',
    level: 'Macro basics',
    minutes: 10,
    description: 'Learn why inflation and interest rates can affect stocks even when company news is quiet.',
    goal: 'Connect economic headlines to company valuations and market moves.',
    video: {
      youtubeId: 'EAKGuN-d07Q',
      title: 'Stock Market Terms for Beginners',
      channel: 'YouTube lesson',
      sourceUrl: 'https://www.youtube.com/watch?v=EAKGuN-d07Q',
    },
    terms: ['fed', 'inflation', 'fomc', 'yield-curve'],
    steps: [
      {
        title: 'Know what inflation changes',
        body: 'Inflation means prices rise, which can pressure consumers and company costs.',
        example: 'If materials and wages rise, profit margins may shrink unless prices rise too.',
        takeaway: 'Inflation can affect both customers and companies.',
      },
      {
        title: 'Understand rates as a price of money',
        body: 'Higher rates make borrowing more expensive and can make future profits less valuable today.',
        example: 'Growth stocks can fall when rates rise because much of their value depends on future earnings.',
        takeaway: 'Rates can change how investors value companies.',
      },
      {
        title: 'Watch the Fed calendar',
        body: 'Fed meetings and inflation reports can move the whole market.',
        example: 'A surprise inflation report can affect indexes before any company releases news.',
        takeaway: 'Macro events can move even strong companies.',
      },
    ],
    quickCheck: {
      question: 'Why can higher interest rates pressure growth stocks?',
      choices: ['Future profits may be valued less today', 'The ticker disappears', 'Revenue is no longer counted'],
      answer: 'Future profits may be valued less today',
      explanation: 'Higher rates can reduce how much investors are willing to pay for future earnings.',
    },
  },
  {
    id: 'portfolio-routine',
    title: 'Building a Study Portfolio',
    level: 'Research system',
    minutes: 9,
    description: 'Turn watchlists into a simple portfolio study routine with notes, reasons, and review dates.',
    goal: 'Create a repeatable process for learning from companies over time.',
    video: {
      youtubeId: 'p7HKvqRI_Bo',
      title: 'How does the stock market work?',
      channel: 'TED-Ed',
      sourceUrl: 'https://www.youtube.com/watch?v=p7HKvqRI_Bo',
    },
    terms: ['portfolio-rebalancing', 'dollar-cost-averaging', 'diversification', 'return'],
    steps: [
      {
        title: 'Write a reason for every ticker',
        body: 'A study portfolio should explain why each company is there.',
        example: 'A reason could be earnings next week, strong margins, or learning about semiconductors.',
        takeaway: 'A ticker without a reason is just noise.',
      },
      {
        title: 'Review on a schedule',
        body: 'Set a repeatable time to check notes, news, filings, and price changes.',
        example: 'A weekly review can catch new earnings dates or changed guidance.',
        takeaway: 'Routine beats random checking.',
      },
      {
        title: 'Track what changed',
        body: 'Update notes when facts change instead of protecting your first opinion.',
        example: 'If revenue slowed, rewrite the thesis and ask what caused it.',
        takeaway: 'Good researchers change their view when evidence changes.',
      },
    ],
    quickCheck: {
      question: 'What makes a study portfolio useful?',
      choices: ['Every ticker has a reason and review plan', 'It has as many random stocks as possible', 'It ignores new facts'],
      answer: 'Every ticker has a reason and review plan',
      explanation: 'A study portfolio helps you learn when each ticker has a question, note, and review habit.',
    },
  },
  {
    id: 'red-flags',
    title: 'Red Flags and Hype Checks',
    level: 'Safety habits',
    minutes: 8,
    description: 'Learn warning signs in stocks, headlines, and social media before trusting a story.',
    goal: 'Spot when excitement is running ahead of evidence.',
    video: {
      youtubeId: 'EAKGuN-d07Q',
      title: 'Stock Market Terms for Beginners',
      channel: 'YouTube lesson',
      sourceUrl: 'https://www.youtube.com/watch?v=EAKGuN-d07Q',
    },
    terms: ['speculation', 'short-selling', 'margin', 'penny-stock'],
    steps: [
      {
        title: 'Be careful with hype words',
        body: 'Words like guaranteed, moon, or can’t lose are warning signs because markets are uncertain.',
        example: 'A post promising fast money without sources should not be treated like research.',
        takeaway: 'Real research explains risks, not just upside.',
      },
      {
        title: 'Check business proof',
        body: 'Look for revenue, profit, cash, filings, and customer demand before trusting a story.',
        example: 'A company can have exciting technology but weak sales.',
        takeaway: 'A good story still needs numbers.',
      },
      {
        title: 'Respect leverage risk',
        body: 'Borrowed money can make gains bigger, but it can also make losses much worse.',
        example: 'Buying on margin can lead to a margin call if the position falls.',
        takeaway: 'Leverage raises risk faster than many beginners expect.',
      },
    ],
    quickCheck: {
      question: 'What is a major red flag in market content?',
      choices: ['Guaranteed profit with no risk', 'A source link to a filing', 'A clear explanation of downside'],
      answer: 'Guaranteed profit with no risk',
      explanation: 'No stock is guaranteed. Content that hides risk is not research.',
    },
  },
]

const glossaryStudyEnhancements: Record<string, Partial<GlossaryTerm>> = {
  stock: {
    brief: 'A stock is a small ownership claim on a real company.',
    whyItMatters: 'When you buy stock, your result depends on what investors think the company can earn in the future.',
    realWorldExample: 'If a company grows sales and profit for years, investors may value each share more.',
    commonMistake: 'Do not treat a stock like a scoreboard number. It is connected to a business.',
    relatedTermIds: ['share', 'market-cap', 'ticker-symbol'],
  },
  'ticker-symbol': {
    brief: 'A ticker is the short code used to search and trade a stock.',
    whyItMatters: 'Tickers help you find the right company quickly, but similar tickers can point to different businesses.',
    realWorldExample: 'AAPL is Apple. MSFT is Microsoft. The code is easier to search than the full company name.',
    commonMistake: 'Do not assume a ticker tells you what the company does.',
    relatedTermIds: ['stock', 'share'],
  },
  'market-cap': {
    brief: 'Market cap is the stock market value of the whole company.',
    whyItMatters: 'It helps you compare company size and understand whether a business is tiny, mid-sized, or huge.',
    realWorldExample: 'If a company has 1 billion shares and each share is $50, the market cap is $50 billion.',
    commonMistake: 'Market cap does not tell you if a stock is cheap. It only tells you company size.',
    quickCheck: {
      question: 'What does market cap measure?',
      choices: ['Company size in the stock market', 'Daily profit', 'The number of news articles'],
      answer: 'Company size in the stock market',
      explanation: 'Market cap estimates the value of all shares together.',
    },
    relatedTermIds: ['stock', 'share', 'pe-ratio'],
  },
  'pe-ratio': {
    brief: 'P/E compares a stock price with the profit the company earns per share.',
    whyItMatters: 'It shows how much investors are paying for each dollar of earnings.',
    realWorldExample: 'A P/E of 25 means investors pay about $25 for $1 of yearly earnings.',
    commonMistake: 'A low P/E is not always good. It can mean investors expect slower growth or higher risk.',
    quickCheck: {
      question: 'A high P/E usually means investors expect what?',
      choices: ['More future growth', 'No trading volume', 'A smaller ticker'],
      answer: 'More future growth',
      explanation: 'High P/E often means investors are willing to pay more because they expect future growth.',
    },
    relatedTermIds: ['eps', 'market-cap', 'value-stock'],
  },
  eps: {
    brief: 'EPS means earnings per share, or company profit divided across each share.',
    whyItMatters: 'It helps investors compare profit with the stock price and with past quarters.',
    realWorldExample: 'If a company earns $100 million and has 50 million shares, EPS is $2.',
    commonMistake: 'EPS can rise because profit rose, but it can also rise if the company has fewer shares.',
    quickCheck: {
      question: 'EPS is mainly about what?',
      choices: ['Profit per share', 'Revenue before costs', 'How fast news spreads'],
      answer: 'Profit per share',
      explanation: 'EPS divides company earnings across the shares investors own.',
    },
    relatedTermIds: ['pe-ratio', 'revenue', 'profit-margin'],
  },
  volume: {
    brief: 'Volume is how many shares traded during a period of time.',
    whyItMatters: 'High volume can show that many investors are reacting to new information.',
    realWorldExample: 'If volume is much higher than normal after earnings, the market is paying attention.',
    commonMistake: 'High volume does not tell you direction by itself. You still need price and news context.',
    relatedTermIds: ['volatility', 'market-order', 'liquidity'],
  },
  revenue: {
    brief: 'Revenue is the money a company brings in from sales before costs.',
    whyItMatters: 'Revenue shows demand, but it does not show how much money the company kept.',
    realWorldExample: 'A store may sell $1,000 of products, but profit depends on rent, workers, shipping, and supplies.',
    commonMistake: 'Do not confuse revenue with profit.',
    relatedTermIds: ['profit-margin', 'eps'],
  },
  'profit-margin': {
    brief: 'Profit margin shows how much of each sales dollar becomes profit.',
    whyItMatters: 'Margins help you see whether a company is getting more efficient or losing power over costs.',
    realWorldExample: 'A 20 percent margin means the company keeps about 20 cents of profit from each sales dollar.',
    commonMistake: 'A company can grow revenue while margins shrink.',
    relatedTermIds: ['revenue', 'eps'],
  },
  sec: {
    brief: 'The SEC is the US agency that oversees public company market rules.',
    whyItMatters: 'SEC filings are official sources, so they are useful when headlines are unclear.',
    realWorldExample: 'A 10-K, 10-Q, or 8-K can confirm what a company officially reported.',
    commonMistake: 'Do not rely only on summaries when an official filing is available.',
    relatedTermIds: ['audit', 'fiscal-year'],
  },
  volatility: {
    brief: 'Volatility means how much the price moves up and down.',
    whyItMatters: 'A volatile stock can change fast, which makes risk harder to manage.',
    realWorldExample: 'A stock that moves 8 percent in one day is more volatile than one that moves 1 percent.',
    commonMistake: 'Volatility is not the same as bad. It means the ride is less steady.',
    relatedTermIds: ['volume', 'beta'],
  },
  etf: {
    brief: 'An ETF is a basket of investments that trades like one stock.',
    whyItMatters: 'ETFs can help you study or invest in a whole sector or index without picking one company.',
    realWorldExample: 'An S&P 500 ETF gives exposure to many large US companies at once.',
    commonMistake: 'An ETF can still lose money if the basket it owns falls.',
    relatedTermIds: ['index', 'diversification'],
  },
}

export function enrichGlossaryTerm(term: GlossaryTerm): GlossaryTerm {
  const enhancement = glossaryStudyEnhancements[term.id] || {}
  return {
    ...term,
    ...enhancement,
    brief: enhancement.brief || term.brief || term.definition,
    whyItMatters: enhancement.whyItMatters || term.whyItMatters || term.detailedExample || 'This term helps you read market stories with more context.',
    realWorldExample: enhancement.realWorldExample || term.realWorldExample || term.example,
    commonMistake: enhancement.commonMistake || term.commonMistake || 'Do not use this idea alone. Compare it with the chart, news, and company facts.',
    relatedTermIds: enhancement.relatedTermIds || term.relatedTermIds || [],
  }
}
