import type { GlossaryTerm, StudyModule } from './types'

export const studyModules: StudyModule[] = [
  {
    id: 'reading-stock-page',
    title: 'Reading a Stock Page',
    level: 'Start here',
    minutes: 8,
    description: 'Study the order to read a company page so prices, charts, news, and filings feel connected.',
    goal: 'Leave with a simple research routine you can repeat on any ticker.',
    terms: ['stock', 'ticker-symbol', 'market-cap', 'volume'],
    steps: [
      {
        title: 'Start with the business',
        body: 'Before the chart, ask what the company sells, who buys it, and how it makes money.',
        example: 'For Apple, the business includes iPhones, Macs, services, and subscriptions.',
        takeaway: 'A price move makes more sense when you know what the business actually does.',
      },
      {
        title: 'Read the price move in context',
        body: 'A stock being up or down today is only one clue. Compare it with the 52-week high, 52-week low, and recent news.',
        example: 'A 3 percent drop may be small if the stock doubled this year, but large if the company also missed earnings.',
        takeaway: 'Always ask what changed, not just whether the price moved.',
      },
      {
        title: 'Connect the sources',
        body: 'Use news for the event, filings for official company facts, and notes for your own questions.',
        example: 'If a headline says sales slowed, check the latest 10-Q or earnings report for revenue and guidance.',
        takeaway: 'Good research compares sources instead of trusting one headline.',
      },
    ],
    quickCheck: {
      question: 'What should you check before reacting to a price move?',
      choices: ['Only today price', 'The business, chart, news, and filings', 'Only social media posts'],
      answer: 'The business, chart, news, and filings',
      explanation: 'A stock move needs context. The business, chart, news, and filings help explain what changed.',
    },
  },
  {
    id: 'key-stats',
    title: 'Key Stats',
    level: 'Core skill',
    minutes: 10,
    description: 'Decode market cap, P/E, EPS, volume, and yearly ranges without memorizing finance jargon.',
    goal: 'Understand what each number can tell you and what it cannot tell you by itself.',
    terms: ['market-cap', 'pe-ratio', 'eps', 'volume'],
    steps: [
      {
        title: 'Use market cap for size',
        body: 'Market cap estimates the total stock market value of a company.',
        example: 'A company worth $2 trillion is usually more stable than a tiny company, but it may also grow more slowly.',
        takeaway: 'Market cap tells you size, not whether the stock is cheap or expensive.',
      },
      {
        title: 'Use P/E to compare price and profit',
        body: 'P/E shows how much investors pay for each dollar of company profit.',
        example: 'A P/E of 30 means investors pay about $30 for $1 of yearly earnings.',
        takeaway: 'High P/E can mean growth hopes, but it can also mean the price is stretched.',
      },
      {
        title: 'Use EPS and volume for signal',
        body: 'EPS shows profit per share. Volume shows how many shares are trading.',
        example: 'Rising EPS with heavy volume can mean investors are paying attention to new information.',
        takeaway: 'Numbers work best when you compare them together.',
      },
    ],
    quickCheck: {
      question: 'What does P/E compare?',
      choices: ['Stock price and company profit', 'News stories and filings', 'Volume and market cap'],
      answer: 'Stock price and company profit',
      explanation: 'P/E compares the stock price with earnings, which are company profit per share.',
    },
  },
  {
    id: 'earnings',
    title: 'Earnings',
    level: 'Research habit',
    minutes: 9,
    description: 'Understand what earnings reports are and why stocks can move even when a company made money.',
    goal: 'Know how to read EPS, revenue, margins, and guidance like a student researcher.',
    terms: ['eps', 'revenue', 'profit-margin', 'fiscal-year'],
    steps: [
      {
        title: 'Separate revenue from profit',
        body: 'Revenue is money from sales. Profit is what is left after costs.',
        example: 'A company can sell more products but still earn less if costs rise faster than sales.',
        takeaway: 'More sales do not always mean a stronger business.',
      },
      {
        title: 'Compare actual results with expectations',
        body: 'Stocks often react to whether the company beat or missed what analysts expected.',
        example: 'EPS of $2.10 can look strong, but if investors expected $2.40, the stock may fall.',
        takeaway: 'The market reacts to surprise, not just the raw number.',
      },
      {
        title: 'Watch guidance',
        body: 'Guidance is what management says about the future.',
        example: 'If a company says next quarter may be slower, investors may care more about that than last quarter.',
        takeaway: 'Future expectations can move prices more than past results.',
      },
    ],
    quickCheck: {
      question: 'Why can a stock fall after the company reports a profit?',
      choices: ['Profit is always bad', 'Results or guidance may be worse than expected', 'Filings are not important'],
      answer: 'Results or guidance may be worse than expected',
      explanation: 'Investors compare results with expectations and listen closely to guidance about the future.',
    },
  },
  {
    id: 'sec-filings',
    title: 'SEC Filings',
    level: 'Official sources',
    minutes: 11,
    description: 'Study the common filing types so official company documents feel less confusing.',
    goal: 'Know where to look for annual facts, quarterly updates, major events, and voting details.',
    terms: ['sec', 'fiscal-year', 'audit', 'insider-trading'],
    steps: [
      {
        title: 'Use 10-K for the full yearly story',
        body: 'A 10-K is the annual report. It covers the business, risks, financial statements, and management discussion.',
        example: 'If you want to know the biggest risks a company lists for itself, start with the 10-K.',
        takeaway: 'The 10-K is slower to read, but it is one of the most complete sources.',
      },
      {
        title: 'Use 10-Q for quarterly updates',
        body: 'A 10-Q is a shorter quarterly report that updates sales, profit, cash, and risks.',
        example: 'If a headline says demand changed this quarter, the 10-Q can show the numbers behind it.',
        takeaway: 'The 10-Q helps you check whether the story is showing up in the results.',
      },
      {
        title: 'Use 8-K and proxy filings for events',
        body: 'An 8-K reports major events. A proxy filing explains voting, board details, and executive pay.',
        example: 'A new CEO, big deal, or major company update often appears in an 8-K.',
        takeaway: 'Different filing types answer different research questions.',
      },
    ],
    quickCheck: {
      question: 'Which filing is usually the annual report?',
      choices: ['10-K', '8-K', 'DEF 14A'],
      answer: '10-K',
      explanation: 'A 10-K is the full annual report. A 10-Q is quarterly, and an 8-K covers major events.',
    },
  },
  {
    id: 'news',
    title: 'Market News',
    level: 'Source reading',
    minutes: 8,
    description: 'Read headlines without getting pulled into panic, hype, or one-sided stories.',
    goal: 'Turn a headline into a clear question you can verify with data.',
    terms: ['ticker-symbol', 'sector-rotation', 'volatility', 'revenue'],
    steps: [
      {
        title: 'Find the actual event',
        body: 'Separate what happened from how people reacted.',
        example: 'A headline may say a stock plunged, but the event might be lower guidance or a missed profit target.',
        takeaway: 'The event matters more than the dramatic wording.',
      },
      {
        title: 'Check if it is company-specific or market-wide',
        body: 'A stock can move because of its own news or because the whole sector is moving.',
        example: 'A chip stock may rise because its earnings were strong or because the entire semiconductor group is rising.',
        takeaway: 'Compare the company with peers before deciding what the headline means.',
      },
      {
        title: 'Write one question',
        body: 'Turn every story into one research question.',
        example: 'If layoffs are announced, ask whether revenue is slowing, costs are too high, or margins are under pressure.',
        takeaway: 'A good question is more useful than a fast opinion.',
      },
    ],
    quickCheck: {
      question: 'What is the best first move after reading a dramatic headline?',
      choices: ['React fast', 'Find the event and verify it', 'Ignore all news'],
      answer: 'Find the event and verify it',
      explanation: 'A headline is a starting point. The next step is checking the event against data and official sources.',
    },
  },
  {
    id: 'watchlist',
    title: 'Building a Watchlist',
    level: 'Daily routine',
    minutes: 7,
    description: 'Use a watchlist as a study queue, not just a list of prices.',
    goal: 'Save companies with a reason, track key words, and update your notes over time.',
    terms: ['ticker-symbol', 'sector-rotation', 'volume', 'support-resistance'],
    steps: [
      {
        title: 'Save with a reason',
        body: 'Every ticker should have a reason it belongs on your list.',
        example: 'A reason could be new product cycle, earnings next week, falling margins, or a sector you want to study.',
        takeaway: 'A watchlist is stronger when every ticker has a question attached.',
      },
      {
        title: 'Track the words that matter',
        body: 'Keyword alerts help you notice repeated themes in news and filings.',
        example: 'Words like margin, guidance, debt, demand, and inventory can point to important changes.',
        takeaway: 'Repeated words often reveal the real story behind the price.',
      },
      {
        title: 'Review, then update your view',
        body: 'Use notes to write what you believed and what new data changed.',
        example: 'If your note said demand is strong, update it when the next report shows weaker sales.',
        takeaway: 'Good research changes when the facts change.',
      },
    ],
    quickCheck: {
      question: 'What makes a watchlist useful for studying?',
      choices: ['Saving random tickers', 'Saving tickers with questions and notes', 'Only checking the price once'],
      answer: 'Saving tickers with questions and notes',
      explanation: 'A study watchlist connects tickers to questions, sources, notes, and future checks.',
    },
  },
]

const glossaryStudyEnhancements: Record<string, Partial<GlossaryTerm>> = {
  stock: {
    brief: 'A stock is a small ownership claim on a real company.',
    whyItMatters: 'When you buy stock, your result depends on what investors think the company can earn in the future.',
    realWorldExample: 'If a company grows sales and profit for years, investors may value each share more.',
    commonMistake: 'Do not treat a stock like a scoreboard number. It is connected to a business.',
    relatedTermIds: ['share', 'market-cap', 'ticker-symbol'],
  },
  'ticker-symbol': {
    brief: 'A ticker is the short code used to search and trade a stock.',
    whyItMatters: 'Tickers help you find the right company quickly, but similar tickers can point to different businesses.',
    realWorldExample: 'AAPL is Apple. MSFT is Microsoft. The code is easier to search than the full company name.',
    commonMistake: 'Do not assume a ticker tells you what the company does.',
    relatedTermIds: ['stock', 'share'],
  },
  'market-cap': {
    brief: 'Market cap is the stock market value of the whole company.',
    whyItMatters: 'It helps you compare company size and understand whether a business is tiny, mid-sized, or huge.',
    realWorldExample: 'If a company has 1 billion shares and each share is $50, the market cap is $50 billion.',
    commonMistake: 'Market cap does not tell you if a stock is cheap. It only tells you company size.',
    quickCheck: {
      question: 'What does market cap measure?',
      choices: ['Company size in the stock market', 'Daily profit', 'The number of news articles'],
      answer: 'Company size in the stock market',
      explanation: 'Market cap estimates the value of all shares together.',
    },
    relatedTermIds: ['stock', 'share', 'pe-ratio'],
  },
  'pe-ratio': {
    brief: 'P/E compares a stock price with the profit the company earns per share.',
    whyItMatters: 'It shows how much investors are paying for each dollar of earnings.',
    realWorldExample: 'A P/E of 25 means investors pay about $25 for $1 of yearly earnings.',
    commonMistake: 'A low P/E is not always good. It can mean investors expect slower growth or higher risk.',
    quickCheck: {
      question: 'A high P/E usually means investors expect what?',
      choices: ['More future growth', 'No trading volume', 'A smaller ticker'],
      answer: 'More future growth',
      explanation: 'High P/E often means investors are willing to pay more because they expect future growth.',
    },
    relatedTermIds: ['eps', 'market-cap', 'value-stock'],
  },
  eps: {
    brief: 'EPS means earnings per share, or company profit divided across each share.',
    whyItMatters: 'It helps investors compare profit with the stock price and with past quarters.',
    realWorldExample: 'If a company earns $100 million and has 50 million shares, EPS is $2.',
    commonMistake: 'EPS can rise because profit rose, but it can also rise if the company has fewer shares.',
    quickCheck: {
      question: 'EPS is mainly about what?',
      choices: ['Profit per share', 'Revenue before costs', 'How fast news spreads'],
      answer: 'Profit per share',
      explanation: 'EPS divides company earnings across the shares investors own.',
    },
    relatedTermIds: ['pe-ratio', 'revenue', 'profit-margin'],
  },
  volume: {
    brief: 'Volume is how many shares traded during a period of time.',
    whyItMatters: 'High volume can show that many investors are reacting to new information.',
    realWorldExample: 'If volume is much higher than normal after earnings, the market is paying attention.',
    commonMistake: 'High volume does not tell you direction by itself. You still need price and news context.',
    relatedTermIds: ['volatility', 'market-order', 'liquidity'],
  },
  revenue: {
    brief: 'Revenue is the money a company brings in from sales before costs.',
    whyItMatters: 'Revenue shows demand, but it does not show how much money the company kept.',
    realWorldExample: 'A store may sell $1,000 of products, but profit depends on rent, workers, shipping, and supplies.',
    commonMistake: 'Do not confuse revenue with profit.',
    relatedTermIds: ['profit-margin', 'eps'],
  },
  'profit-margin': {
    brief: 'Profit margin shows how much of each sales dollar becomes profit.',
    whyItMatters: 'Margins help you see whether a company is getting more efficient or losing power over costs.',
    realWorldExample: 'A 20 percent margin means the company keeps about 20 cents of profit from each sales dollar.',
    commonMistake: 'A company can grow revenue while margins shrink.',
    relatedTermIds: ['revenue', 'eps'],
  },
  sec: {
    brief: 'The SEC is the US agency that oversees public company market rules.',
    whyItMatters: 'SEC filings are official sources, so they are useful when headlines are unclear.',
    realWorldExample: 'A 10-K, 10-Q, or 8-K can confirm what a company officially reported.',
    commonMistake: 'Do not rely only on summaries when an official filing is available.',
    relatedTermIds: ['audit', 'fiscal-year'],
  },
  volatility: {
    brief: 'Volatility means how much the price moves up and down.',
    whyItMatters: 'A volatile stock can change fast, which makes risk harder to manage.',
    realWorldExample: 'A stock that moves 8 percent in one day is more volatile than one that moves 1 percent.',
    commonMistake: 'Volatility is not the same as bad. It means the ride is less steady.',
    relatedTermIds: ['volume', 'beta'],
  },
  etf: {
    brief: 'An ETF is a basket of investments that trades like one stock.',
    whyItMatters: 'ETFs can help you study or invest in a whole sector or index without picking one company.',
    realWorldExample: 'An S&P 500 ETF gives exposure to many large US companies at once.',
    commonMistake: 'An ETF can still lose money if the basket it owns falls.',
    relatedTermIds: ['index', 'diversification'],
  },
}

export function enrichGlossaryTerm(term: GlossaryTerm): GlossaryTerm {
  const enhancement = glossaryStudyEnhancements[term.id] || {}
  return {
    ...term,
    ...enhancement,
    brief: enhancement.brief || term.brief || term.definition,
    whyItMatters: enhancement.whyItMatters || term.whyItMatters || term.detailedExample || 'This term helps you read market stories with more context.',
    realWorldExample: enhancement.realWorldExample || term.realWorldExample || term.example,
    commonMistake: enhancement.commonMistake || term.commonMistake || 'Do not use this idea alone. Compare it with the chart, news, and company facts.',
    relatedTermIds: enhancement.relatedTermIds || term.relatedTermIds || [],
  }
}
